#!/bin/bash

echo "🌱 Green House Control - Solutions d'accès iPhone"
echo "================================================"
echo ""
echo "PROBLÈME: Safari iPhone essaie de forcer HTTPS"
echo ""
echo "📱 SOLUTIONS POUR VOTRE iPHONE:"
echo ""
echo "1. Dans Safari iPhone, tapez EXACTEMENT:"
echo "   http://192.168.178.21:3000"
echo "   (ne PAS oublier le 'http://')"
echo ""
echo "2. Si Safari force HTTPS, essayez:"
echo "   - Effacer le cache Safari"
echo "   - Redémarrer Safari complètement"  
echo "   - Utiliser la navigation privée"
echo ""
echo "3. Alternative - Utiliser Chrome sur iPhone:"
echo "   - Installer Chrome depuis App Store"
echo "   - Ouvrir: http://192.168.178.21:3000"
echo ""
echo "4. Test de connectivité depuis MacBook:"
curl -s -I http://192.168.178.21:3000 | head -1
echo ""
echo "5. Si ça ne marche toujours pas:"
echo "   - Vérifiez que iPhone et MacBook sont sur le même WiFi"
echo "   - Désactivez temporairement le firewall macOS"
echo ""
echo "📋 Adresses disponibles:"
echo "   MacBook:  http://localhost:3000"
echo "   iPhone:   http://192.168.178.21:3000"
echo "   Autres:   http://192.168.178.21:3000"
echo ""