[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Configuration des pins et fonctionnalités
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

; Bibliothèques requises
lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4

; Configuration série
monitor_speed = 115200
upload_speed = 921600

; Options de compilation
build_flags = 
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_ARDUHAL_ESP_LOG

; Configuration mémoire
board_build.partitions = huge_app.csv